---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ .Values.metadata.argocd.clusterSet }}
  namespace: {{ .Values.metadata.argocd.namespace }}
spec:
  clusterSet: {{ .Values.metadata.argocd.clusterSet }}
